# Generated by Django 5.2.16 on 2026-07-15 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "departments",
                "ordering": ["department_name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division_name", models.CharField(max_length=255)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="orgunits.department",
                    ),
                ),
            ],
            options={
                "db_table": "divisions",
                "ordering": ["division_name"],
            },
        ),
    ]
