<?php
// export_orders_pdf.php — server-side PDF export of all food orders (no pagination)
if (session_status() === PHP_SESSION_NONE) session_start();

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../includes/auth_helpers.php';
require_once __DIR__ . '/../includes/role_switcher.php';
require_once __DIR__ . '/../../vendor/autoload.php';

enforceActiveUser($conn);
requireAnyRole(['user', 'agent', 'admin', 'superadmin']);

// ---------------------------
// Filters (mirrors all_orders.php)
// ---------------------------
$selected_date   = $_GET['date']   ?? date('Y-m-d');
$selected_outlet = trim($_GET['outlet'] ?? '');
$selected_type   = trim($_GET['type']   ?? '');

$baseSql = "FROM orders o
            JOIN users u ON o.user_id = u.id
            LEFT JOIN outlets ou ON o.outlet_id = ou.id
            WHERE DATE(o.order_date) = ?";

$params = [$selected_date];
$types  = 's';

if ($selected_outlet !== '') {
    if ($selected_outlet === 'cash_request') {
        $baseSql .= " AND o.order_type = 'cash_request'";
    } else {
        $baseSql .= " AND ou.name LIKE ?";
        $params[] = '%' . $selected_outlet . '%';
        $types   .= 's';
    }
}

if ($selected_type !== '') {
    $baseSql .= " AND o.order_type = ?";
    $params[] = $selected_type;
    $types   .= 's';
}

// ---------------------------
// Totals
// ---------------------------
$countSql  = "SELECT COUNT(*) as cnt,
                     COALESCE(SUM(o.total_amount), 0) AS total_amount_sum,
                     COALESCE(SUM(o.overfee_amount), 0) AS total_overfees,
                     COALESCE(SUM(o.total_amount + o.overfee_amount), 0) AS grand_total
              " . $baseSql;
$countStmt = $conn->prepare($countSql);
$bindNames = [$types];
foreach ($params as $i => $_) $bindNames[] = &$params[$i];
call_user_func_array([$countStmt, 'bind_param'], $bindNames);
$countStmt->execute();
$totals        = $countStmt->get_result()->fetch_assoc();
$totalRows     = (int)$totals['cnt'];
$totalAmount   = (float)$totals['total_amount_sum'];
$totalOverfees = (float)$totals['total_overfees'];
$grandTotal    = (float)$totals['grand_total'];
$countStmt->close();

// ---------------------------
// Fetch all rows (no LIMIT)
// ---------------------------
$sql = "SELECT o.id, o.order_date, o.order_type, o.order_items, o.total_amount, o.overfee_amount, o.notes,
               u.username AS user_name, u.email, u.department,
               ou.name AS outlet_name
        " . $baseSql . "
        ORDER BY o.created_at DESC";

$stmt      = $conn->prepare($sql);
$bindNames2 = [$types];
foreach ($params as $i => $_) $bindNames2[] = &$params[$i];
call_user_func_array([$stmt, 'bind_param'], $bindNames2);
$stmt->execute();
$rows = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();
$conn->close();

// ---------------------------
// Build PDF with mPDF
// ---------------------------
$mpdf = new \Mpdf\Mpdf([
    'orientation' => 'L',
    'margin_top'  => 20,
    'margin_left' => 10,
    'margin_right'=> 10,
]);

$generatedBy = $_SESSION['user']['username'];
$dateNow     = date('Y-m-d H:i');

// Filter summary line
$filterParts = ['Date: ' . htmlspecialchars($selected_date)];
if ($selected_outlet !== '') $filterParts[] = 'Outlet: ' . htmlspecialchars($selected_outlet);
if ($selected_type   !== '') $filterParts[] = 'Type: '   . htmlspecialchars($selected_type);
$filterLine = implode(' &nbsp;|&nbsp; ', $filterParts);

$html  = '<h2 style="text-align:center;margin-bottom:4px;">PSPF Food Orders — Delivery Receipt</h2>';
$html .= '<p style="text-align:center;font-size:10px;color:#555;">' . $filterLine . '</p>';
$html .= '<p style="text-align:center;font-size:10px;color:#555;">Generated by ' . htmlspecialchars($generatedBy) . ' &nbsp;|&nbsp; ' . $dateNow . ' &nbsp;|&nbsp; Total Orders: ' . $totalRows . '</p>';

$html .= '
<table border="1" cellpadding="4" cellspacing="0" width="100%"
       style="border-collapse:collapse;font-size:9px;">
<thead>
  <tr style="background:#2980b9;color:#fff;font-weight:bold;">
    <th>Order ID</th>
    <th>User</th>
    <th>Department</th>
    <th>Outlet / Type</th>
    <th>Order Details</th>
    <th>Total Amount</th>
    <th>Extra Fee</th>
    <th>Signature</th>
  </tr>
</thead>
<tbody>';

foreach ($rows as $i => $row) {
    $bg          = $i % 2 === 0 ? '#ffffff' : '#f5f5f5';
    $outletLabel = $row['order_type'] === 'cash_request'
        ? 'Cash Request'
        : htmlspecialchars($row['outlet_name'] ?? '');
    $details     = htmlspecialchars($row['order_items'] ?? '');
    if (!empty($row['notes'])) $details .= '<br><em>' . htmlspecialchars($row['notes']) . '</em>';

    $html .= '<tr style="background:' . $bg . ';">';
    $html .= '<td>#' . $row['id'] . '</td>';
    $html .= '<td>' . htmlspecialchars($row['user_name']) . '<br><small>' . htmlspecialchars($row['email']) . '</small></td>';
    $html .= '<td>' . htmlspecialchars($row['department'] ?? '') . '</td>';
    $html .= '<td>' . $outletLabel . '</td>';
    $html .= '<td>' . $details . '</td>';
    $html .= '<td style="text-align:right;">E ' . number_format($row['total_amount'], 2) . '</td>';
    $html .= '<td style="text-align:right;">' . ($row['overfee_amount'] > 0 ? 'E ' . number_format($row['overfee_amount'], 2) : '-') . '</td>';
    $html .= '<td>&nbsp;</td>';
    $html .= '</tr>';
}

$html .= '</tbody></table>';

// Totals summary
$html .= '
<br>
<table border="0" cellpadding="4" cellspacing="0" width="40%" style="margin-left:auto;font-size:10px;">
  <tr><td>Total Orders:</td><td style="text-align:right;"><strong>' . $totalRows . '</strong></td></tr>
  <tr><td>Order Total:</td><td style="text-align:right;">E ' . number_format($totalAmount, 2) . '</td></tr>
  <tr><td>Extra Fees:</td><td style="text-align:right;">E ' . number_format($totalOverfees, 2) . '</td></tr>
  <tr style="background:#d4edda;"><td><strong>Grand Total:</strong></td><td style="text-align:right;"><strong>E ' . number_format($grandTotal, 2) . '</strong></td></tr>
</table>
<br>
<table border="0" cellpadding="6" cellspacing="0" width="50%" style="font-size:10px;">
  <tr><td>Received by: ___________________________</td></tr>
  <tr><td>Signature: &nbsp;&nbsp;___________________________</td></tr>
  <tr><td>Date: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;___________________________</td></tr>
</table>';

$mpdf->SetHTMLFooter('<div style="text-align:right;font-size:8px;">Page {PAGENO} of {nbpg}</div>');
$mpdf->WriteHTML($html);
$mpdf->Output('PSPF_Food_Orders_' . $selected_date . '.pdf', 'D');
