# Generated by Django 5.2.16 on 2026-07-15 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ITAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_number", models.CharField(max_length=20, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[("new", "New"), ("change", "Change")],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("department", models.CharField(max_length=255)),
                ("division", models.CharField(blank=True, max_length=255, null=True)),
                ("job_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("justification", models.TextField()),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("claimed", "Claimed"),
                            ("awaiting-director", "Awaiting Director"),
                            ("provisioned", "Provisioned"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pdf_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sharepoint_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="claimed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="it_requests_claimed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        db_column="submitted_by",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="it_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "it_access_requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ITRequestApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("officer-1", "Officer"),
                            ("director", "Director"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("acted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True, null=True)),
                ("sig_kind", models.CharField(blank=True, max_length=20, null=True)),
                ("sig_data", models.TextField(blank=True, null=True)),
                ("actioned_systems", models.TextField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        db_column="approver_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="it_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="it_access.itaccessrequest",
                    ),
                ),
            ],
            options={
                "db_table": "it_request_approvals",
                "ordering": ["acted_at"],
            },
        ),
        migrations.CreateModel(
            name="ITRequestSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("sub_values", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("claimed", "Claimed"),
                            ("actioned", "Actioned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("actioned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actioned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="actioned_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="it_systems_actioned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="claimed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="it_systems_claimed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        db_column="request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="it_access.itaccessrequest",
                    ),
                ),
            ],
            options={
                "db_table": "it_request_systems",
            },
        ),
    ]
