# Generated by Django 5.2.16 on 2026-07-15 12:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgunits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "member_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                (
                    "query_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("query_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_by", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("On Hold", "On Hold"),
                            ("Escalated", "Escalated"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=30,
                    ),
                ),
                (
                    "attachment_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("assigned_to", models.TextField(blank=True, default="")),
                (
                    "last_updated_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        db_column="division_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="orgunits.division",
                    ),
                ),
            ],
            options={
                "db_table": "tickets",
                "ordering": ["-query_date"],
            },
        ),
        migrations.CreateModel(
            name="TicketFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=0)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "submitted_by",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        db_column="ticket_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_feedback",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=30, null=True)),
                ("new_status", models.CharField(max_length=30)),
                ("changed_by", models.CharField(max_length=150)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        db_column="ticket_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "db_table": "ticket_status_logs",
                "ordering": ["-changed_at"],
            },
        ),
    ]
