<?php
// export_admin_pdf.php — server-side PDF export of all tickets (no pagination)
session_start();
require_once '../includes/auth_helpers.php';
require_once '../includes/role_switcher.php';
require_once '../db.php';
require_once '../vendor/autoload.php';

enforceActiveUser($conn);
requireAnyRole(['admin', 'superadmin']);

$activeRole     = getActiveRole();
$UserEmail      = $_SESSION['user']['email'];
$UserDivisionId = (int)($_SESSION['user']['division_id'] ?? 0);

// ---------------------------
// Filters (mirrors admin_view.php)
// ---------------------------
$filter         = $_GET['filter']     ?? '';
$deptFilter     = isset($_GET['department']) && $_GET['department'] !== '' ? $_GET['department'] : '';
$statusFilter   = isset($_GET['status'])     && $_GET['status']     !== '' ? $_GET['status']     : '';
$priorityFilter = isset($_GET['priority'])   && $_GET['priority']   !== '' ? $_GET['priority']   : '';
$assignedFilter = isset($_GET['assigned'])   && $_GET['assigned']   === 'me';

$searchParam  = '%' . $filter . '%';
$whereClauses = [];
$params       = [];
$types        = '';

if (!empty($filter)) {
    $whereClauses[] = "(t.title LIKE ? OR t.description LIKE ? OR t.created_by LIKE ? OR t.assigned_to LIKE ? OR CAST(t.id AS CHAR) LIKE ?)";
    array_push($params, $searchParam, $searchParam, $searchParam, $searchParam, $searchParam);
    $types .= 'sssss';
}

if ($activeRole === 'superadmin' && !empty($deptFilter)) {
    $whereClauses[] = 't.division_id = ?';
    $params[]        = (int)$deptFilter;
    $types          .= 'i';
}

if (!empty($statusFilter)) {
    $whereClauses[] = 't.status = ?';
    $params[]        = $statusFilter;
    $types          .= 's';
}

if (!empty($priorityFilter)) {
    $whereClauses[] = 't.priority = ?';
    $params[]        = $priorityFilter;
    $types          .= 's';
}

if ($activeRole === 'admin') {
    if ($UserDivisionId > 0) {
        $whereClauses[] = 't.division_id = ?';
        $params[]        = $UserDivisionId;
        $types          .= 'i';
    }
    if ($assignedFilter) {
        $whereClauses[] = 't.assigned_to LIKE ?';
        $params[]        = '%' . $UserEmail . '%';
        $types          .= 's';
    }
}

$whereClause = !empty($whereClauses) ? 'WHERE ' . implode(' AND ', $whereClauses) : '';

// ---------------------------
// Fetch all rows (no LIMIT)
// ---------------------------
$sql = "
    SELECT t.id, t.title, t.status, t.priority, t.source, t.region,
           t.member_type, t.phone_number, t.query_date, t.created_by,
           t.assigned_to, d.division_name
    FROM tickets t
    LEFT JOIN users u  ON t.created_by  = u.username
    LEFT JOIN divisions d ON t.division_id = d.id
    $whereClause
    ORDER BY t.query_date DESC
";

$stmt = $conn->prepare($sql);
if (!empty($params)) {
    $stmt->bind_param($types, ...$params);
}
$stmt->execute();
$rows = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt->close();
$conn->close();

// ---------------------------
// Build PDF with mPDF
// ---------------------------
$mpdf = new \Mpdf\Mpdf([
    'orientation' => 'L',
    'margin_top'  => 20,
    'margin_left' => 10,
    'margin_right'=> 10,
]);

$generatedBy = $_SESSION['user']['username'];
$dateNow     = date('Y-m-d H:i');
$total       = count($rows);

$html  = '<h2 style="text-align:center;margin-bottom:4px;">Tickets Report</h2>';
$html .= '<p style="text-align:center;font-size:11px;color:#555;">Generated by ' . htmlspecialchars($generatedBy) . ' &nbsp;|&nbsp; ' . $dateNow . ' &nbsp;|&nbsp; Total: ' . $total . '</p>';

$html .= '
<table border="1" cellpadding="4" cellspacing="0" width="100%"
       style="border-collapse:collapse;font-size:9px;">
<thead>
  <tr style="background:#343a40;color:#fff;font-weight:bold;">
    <th>Ticket ID</th>
    <th>Title</th>
    <th>Status</th>
    <th>Priority</th>
    <th>Source</th>
    <th>Branch</th>
    <th>Member Type</th>
    <th>Division</th>
    <th>Created By</th>
    <th>Assigned To</th>
    <th>Date Submitted</th>
  </tr>
</thead>
<tbody>';

foreach ($rows as $i => $row) {
    $bg = $i % 2 === 0 ? '#ffffff' : '#f2f2f2';
    $html .= '<tr style="background:' . $bg . ';">';
    $html .= '<td>' . htmlspecialchars('TCK-' . str_pad($row['id'], 6, '0', STR_PAD_LEFT)) . '</td>';
    $html .= '<td>' . htmlspecialchars($row['title'])                                        . '</td>';
    $html .= '<td>' . htmlspecialchars($row['status'])                                       . '</td>';
    $html .= '<td>' . htmlspecialchars($row['priority'])                                     . '</td>';
    $html .= '<td>' . htmlspecialchars($row['source'])                                       . '</td>';
    $html .= '<td>' . htmlspecialchars($row['region'])                                       . '</td>';
    $html .= '<td>' . htmlspecialchars($row['member_type'])                                  . '</td>';
    $html .= '<td>' . htmlspecialchars($row['division_name'] ?? '')                          . '</td>';
    $html .= '<td>' . htmlspecialchars($row['created_by'])                                   . '</td>';
    $html .= '<td>' . htmlspecialchars($row['assigned_to'] ?? '')                            . '</td>';
    $html .= '<td>' . htmlspecialchars($row['query_date'])                                   . '</td>';
    $html .= '</tr>';
}

$html .= '</tbody></table>';

$mpdf->SetHTMLFooter('<div style="text-align:right;font-size:8px;">Page {PAGENO} of {nbpg}</div>');
$mpdf->WriteHTML($html);
$mpdf->Output('tickets_report_' . date('Ymd_His') . '.pdf', 'D');
